services:
  app:
    image: go-todolist-app
    container_name: go_app
    build: .
    depends_on:
      - go_db
    ports:
      - "8080:8080"
    # volumes:
    #   - .:/app
    env_file:
      - .env

  go_db:
    image: postgres:12
    container_name: go_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}