definitions:
  main.Task:
    properties:
      description:
        type: string
      id:
        type: integer
      status:
        $ref: '#/definitions/main.taskStatus'
      title:
        type: string
    required:
    - status
    - title
    type: object
  main.taskStatus:
    enum:
    - Pending
    - In Progress
    - Completed
    type: string
    x-enum-varnames:
    - StatusPending
    - StatusInProgress
    - StatusCompleted
host: localhost:8080
info:
  contact:
    email: adrian.coradini3141592@hotmail.com
    name: Adrian Coradini
  description: REST API para consultar, criar, atualizar e deletas tarefas
  title: REST API To-Do List
  version: 1.0.0
paths:
  /tasks:
    post:
      consumes:
      - application/json
      description: Adiciona uma nova tarefa à lista de tarefas
      parameters:
      - description: Task data
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/main.Task'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Task'
      summary: Adiciona uma nova tarefa
      tags:
      - tasks
swagger: "2.0"
